/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paginadecinema.views;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import paginadecinema.modelo.Diretores;
import paginadecinema.modelo.Filmes;
import paginadecinema.modelo.Roteiristas;
import paginadecinema.modelo.dao.PersistenciaJPA;

/**
 *
 * @author loren
 */
public class TelaGerenciaFilmes extends javax.swing.JDialog {

    /**
     * Creates new form TelaGerenciaFilmes
     */
    public TelaGerenciaFilmes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        listarFilmes();
    }

    PersistenciaJPA persistencia;

    private void listarFilmes() {
        try {
            persistencia = new PersistenciaJPA();
            lstFilmes.clearSelection();
            persistencia.conexaoAberta();
            List<Filmes> filmes = persistencia.getFilmes();
            DefaultListModel modeloLista = new DefaultListModel<>();
            for (Filmes filme : filmes) {
                modeloLista.addElement(filme);
            }
            lstFilmes.setModel(modeloLista);
            persistencia.fecharConexao();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao listar modalidades: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstFilmes = new javax.swing.JList<>();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        jLabel1.setText("Gerenciar Filmes");

        jScrollPane1.setViewportView(lstFilmes);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            Filmes f = new Filmes();

            // Get filme name
            f.setNomeFilme(JOptionPane.showInputDialog("Informe o nome do filme: "));

            // Get and parse dataEstreia
            String dataEstreiaStr = JOptionPane.showInputDialog("Informe a data de estreia (dd/MM/yyyy):");
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Calendar dataEstreia = Calendar.getInstance();
            dataEstreia.setTime(sdf.parse(dataEstreiaStr));
            f.setDataEstreia(dataEstreia);

            // Get and parse notaIMDb
            String notaStr = JOptionPane.showInputDialog("Informe a nota do IMDb:");
            f.setNotaIMDb(Double.parseDouble(notaStr));

            // Get and set Roteirista (assuming you have a method to fetch Roteiristas)
            persistencia = new PersistenciaJPA();
            persistencia.conexaoAberta();
            List<Roteiristas> roteiristas = persistencia.getRoteiristas();
         
            Roteiristas selectedRoteirista = (Roteiristas) JOptionPane.showInputDialog(
                    null,
                    "Selecione o Roteirista:",
                    "Roteirista",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    roteiristas.toArray(),
                    roteiristas.get(0)
            );
            f.setRoteirista(selectedRoteirista);

            // Get and set Diretor (assuming you have a method to fetch Diretores)
            List<Diretores> diretores = persistencia.getDiretores();
            Diretores selectedDiretor = (Diretores) JOptionPane.showInputDialog(
                    null,
                    "Selecione o Diretor:",
                    "Diretor",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    diretores.toArray(),
                    diretores.get(0)
            );
            f.setDiretor(selectedDiretor);

            // Persist the new film
            persistencia.persist(f);
            persistencia.fecharConexao();
            listarFilmes(); // Refresh the list
        } catch (Exception ex) {
            Logger.getLogger(TelaGerenciaFilmes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

        Filmes filmeSelecionado = lstFilmes.getSelectedValue();
        if (filmeSelecionado != null) {
            int confirmacaoDel = JOptionPane.showConfirmDialog(rootPane,
                    "Tem certeza que deseja remover o filme " + filmeSelecionado.getNomeFilme() + "?");
            if (confirmacaoDel == JOptionPane.YES_OPTION) {
                try {
                    persistencia = new PersistenciaJPA();
                    persistencia.conexaoAberta();

                    // Recarregar a entidade
                    Filmes filmeGerenciado = (Filmes) persistencia.find(Filmes.class, filmeSelecionado.getIdFilme());

                    if (filmeGerenciado != null) {
                        persistencia.remover(filmeGerenciado);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Filme não encontrado no banco de dados.");
                    }

                    persistencia.fecharConexao();
                    listarFilmes();
                } catch (Exception e) {
                    System.err.println("Erro ao excluir modalidade: " + e.getMessage());
                } finally {
                    persistencia.fecharConexao();
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "Nenhuma modalidade selecionada");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Filmes filmeSelecionado = lstFilmes.getSelectedValue();
    if (filmeSelecionado != null) {
        try {
            persistencia = new PersistenciaJPA();
            persistencia.conexaoAberta();

            // Exibe um diálogo de entrada para o usuário editar o nome do filme
            String novoNome = JOptionPane.showInputDialog(this,
                    "Edite o nome do filme:",
                    filmeSelecionado.getNomeFilme());

            // Se o usuário não cancelar e o novo nome não for nulo ou vazio
            if (novoNome != null && !novoNome.trim().isEmpty()) {
                filmeSelecionado.setNomeFilme(novoNome); // Atualiza o nome do filme
            }

            // Exibe um diálogo de entrada para o usuário editar a data de estreia
            String novaDataEstreiaStr = JOptionPane.showInputDialog(this,
                    "Edite a data de estreia (dd/MM/yyyy):",
                    new SimpleDateFormat("dd/MM/yyyy").format(filmeSelecionado.getDataEstreia().getTime()));
            if (novaDataEstreiaStr != null && !novaDataEstreiaStr.trim().isEmpty()) {
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                Calendar novaDataEstreia = Calendar.getInstance();
                novaDataEstreia.setTime(sdf.parse(novaDataEstreiaStr));
                filmeSelecionado.setDataEstreia(novaDataEstreia); // Atualiza a data de estreia
            }

            // Exibe um diálogo de entrada para o usuário editar a nota do IMDb
            String novaNotaIMDbStr = JOptionPane.showInputDialog(this,
                    "Edite a nota do IMDb:",
                    filmeSelecionado.getNotaIMDb().toString());
            if (novaNotaIMDbStr != null && !novaNotaIMDbStr.trim().isEmpty()) {
                filmeSelecionado.setNotaIMDb(Double.parseDouble(novaNotaIMDbStr)); // Atualiza a nota do IMDb
            }

            // Exibe um diálogo de seleção para o usuário editar o roteirista
            List<Roteiristas> roteiristas = persistencia.getRoteiristas();
            Roteiristas novoRoteirista = (Roteiristas) JOptionPane.showInputDialog(
                    null,
                    "Edite o Roteirista:",
                    "Roteirista",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    roteiristas.toArray(),
                    filmeSelecionado.getRoteirista());
            if (novoRoteirista != null) {
                filmeSelecionado.setRoteirista(novoRoteirista); // Atualiza o roteirista
            }

            // Exibe um diálogo de seleção para o usuário editar o diretor
            List<Diretores> diretores = persistencia.getDiretores();
            Diretores novoDiretor = (Diretores) JOptionPane.showInputDialog(
                    null,
                    "Edite o Diretor:",
                    "Diretor",
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    diretores.toArray(),
                    filmeSelecionado.getDiretor());
            if (novoDiretor != null) {
                filmeSelecionado.setDiretor(novoDiretor); // Atualiza o diretor
            }

            // Persiste as mudanças no banco de dados
            persistencia.merge(filmeSelecionado);

            // Atualiza a lista de filmes exibida
            listarFilmes(); 

        } catch (Exception e) {
            System.err.println("Erro ao editar o filme: " + e.getMessage());
        } finally {
            persistencia.fecharConexao();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um filme para editar.");
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaGerenciaFilmes dialog = new TelaGerenciaFilmes(new javax.swing.JFrame(), true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Filmes> lstFilmes;
    // End of variables declaration//GEN-END:variables
}
